---
- name: wait for aths file on target host
  wait_for:
    state: present
    path: /var/lib/tor/services/ssh/hostname
    delay: 2

- name: fetch ssh aths file
  fetch:
    src: /var/lib/tor/services/ssh/hostname
    dest: ssh-aths-inventory/{{ inventory_hostname }}
    flat: yes
    fail_on_missing: yes

- name: reformat ssh aths file
  local_action: lineinfile
      dest=ssh-aths-inventory/{{ inventory_hostname }}
      regexp='(.*)'
      backrefs=yes
      line='HidServAuth \1'
      state=present
  sudo: no

- name: set hidservauth_entry host fact
  set_fact:
    ansible_ssh_aths_hidservauth_entry: "{{ lookup('file', 'ssh-aths-inventory/'+inventory_hostname) }}"

